Update package.json
"TypeError: require.extensions.hasOwnProperty is not a function" while trying to run the app on Local machine.
Reference: https://stackoverflow.com/questions/44298322/node-8-0-0-and-npm-4-2-0-error-express-load-require-extensions-hasownproperty-is